package com.konakart.app;

/**
 *  The KonaKart Custom Engine - CheckFileAccess - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class CheckFileAccess
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public CheckFileAccess(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void checkFileAccess(String fileName) throws Exception
     {
         kkEng.checkFileAccess(fileName);
     }
}
