package com.konakart.app;

/**
 *  The KonaKart Custom Engine - DeleteCreditCard - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class DeleteCreditCard
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public DeleteCreditCard(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void deleteCreditCard(String sessionId, int cardId) throws Exception
     {
         kkEng.deleteCreditCard(sessionId, cardId);
     }
}
