package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - EditCreditCard - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class EditCreditCard
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public EditCreditCard(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void editCreditCard(String sessionId, CreditCardIf card, CreditCardOptionsIf options) throws Exception
     {
         kkEng.editCreditCard(sessionId, card, options);
     }
}
