package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAddressesPerVendor - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAddressesPerVendor
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAddressesPerVendor(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public AddressIf[] getAddressesPerVendor(VendorIf vendor) throws KKException
     {
         return kkEng.getAddressesPerVendor(vendor);
     }
}
