package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCatalogPerKey - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCatalogPerKey
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCatalogPerKey(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CatalogIf getCatalogPerKey(String catalogKey) throws KKException
     {
         return kkEng.getCatalogPerKey(catalogKey);
     }
}
