package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCustomerWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCustomerWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CustomerIf getCustomerWithOptions(String sessionId, FetchCustomerOptionsIf options) throws KKException
     {
         return kkEng.getCustomerWithOptions(sessionId, options);
     }
}
