package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetOrdersPerCustomerWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetOrdersPerCustomerWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetOrdersPerCustomerWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrdersIf getOrdersPerCustomerWithOptions(DataDescriptorIf dataDesc, String sessionId, int languageId, FetchOrderOptionsIf options) throws KKException
     {
         return kkEng.getOrdersPerCustomerWithOptions(dataDesc, sessionId, languageId, options);
     }
}
