package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetOrderWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetOrderWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetOrderWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrderIf getOrderWithOptions(String sessionId, int orderId, int languageId, FetchOrderOptionsIf options) throws KKException
     {
         return kkEng.getOrderWithOptions(sessionId, orderId, languageId, options);
     }
}
