package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPromotion - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPromotion
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPromotion(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PromotionIf getPromotion(int promotionId, String promotionName, int languageId, FetchPromotionOptionsIf prmOptions, FetchProductOptionsIf prodOptions) throws KKException
     {
         return kkEng.getPromotion(promotionId, promotionName, languageId, prmOptions, prodOptions);
     }
}
