package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetReviewsPerVendor - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetReviewsPerVendor
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetReviewsPerVendor(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ReviewsIf getReviewsPerVendor(DataDescriptorIf dataDesc, int vendorId) throws KKException
     {
         return kkEng.getReviewsPerVendor(dataDesc, vendorId);
     }
}
