package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetStoreForId - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetStoreForId
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetStoreForId(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public StoreIf getStoreForId(String vendorStoreId) throws KKException
     {
         return kkEng.getStoreForId(vendorStoreId);
     }
}
