package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetVendorForId - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetVendorForId
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetVendorForId(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public VendorIf getVendorForId(int vendorId) throws KKException
     {
         return kkEng.getVendorForId(vendorId);
     }
}
