package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetVendorReview - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetVendorReview
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetVendorReview(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ReviewIf getVendorReview(int reviewId) throws KKException
     {
         return kkEng.getVendorReview(reviewId);
     }
}
