package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - LoginWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class LoginWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public LoginWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public LoginResultIf loginWithOptions(LoginInputIf input) throws KKException
     {
         return kkEng.loginWithOptions(input);
     }
}
