package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - NotifySysAdmin - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class NotifySysAdmin
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public NotifySysAdmin(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public EmailIf notifySysAdmin(String message, EmailOptionsIf options) throws KKException
     {
         return kkEng.notifySysAdmin(message, options);
     }
}
