package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SaveOrderWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SaveOrderWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SaveOrderWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int saveOrderWithOptions(String sessionId, OrderIf order, int languageId, SaveOrderOptionsIf options) throws KKException
     {
         return kkEng.saveOrderWithOptions(sessionId, order, languageId, options);
     }
}
