package com.konakart.app;

/**
 *  The KonaKart Custom Engine - SetNewPassword - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SetNewPassword
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SetNewPassword(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void setNewPassword(String adminSession, String customerEmailAddr, int customerId, String newPassword) throws KKException
     {
         kkEng.setNewPassword(adminSession, customerEmailAddr, customerId, newPassword);
     }
}
