package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddCatalogRules - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddCatalogRules
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddCatalogRules(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addCatalogRules(String sessionId, String catalogId, AdminCatalogRule[] rules) throws KKAdminException
     {
         kkAdminEng.addCatalogRules(sessionId, catalogId, rules);
     }
}
