package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddRelatedProductsWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddRelatedProductsWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddRelatedProductsWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addRelatedProductsWithOptions(String sessionId, AdminProduct[] products, int productId, int relationType, AdminProductMgrOptions mgrOptions) throws KKAdminException
     {
         kkAdminEng.addRelatedProductsWithOptions(sessionId, products, productId, relationType, mgrOptions);
     }
}
