package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddVendorToStore - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddVendorToStore
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddVendorToStore(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addVendorToStore(String sessionId, int vendorId, String vendorStoreId) throws KKAdminException
     {
         kkAdminEng.addVendorToStore(sessionId, vendorId, vendorStoreId);
     }
}
