package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - CloneCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class CloneCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public CloneCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCloneCustomerResult cloneCustomer(String sessionId, int cloneCustId, String[] stores) throws KKAdminException
     {
         return kkAdminEng.cloneCustomer(sessionId, cloneCustId, stores);
     }
}
