package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - CopyFiles - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class CopyFiles
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public CopyFiles(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public boolean copyFiles(String sessionId, String[] srcFileNames, String[] dstFileNames) throws KKAdminException
     {
         return kkAdminEng.copyFiles(sessionId, srcFileNames, dstFileNames);
     }
}
