package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - CreateMailingList - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class CreateMailingList
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public CreateMailingList(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void createMailingList(String sessionId, AdminCustomerSearch search, AdminMailListOptions listOptions) throws KKAdminException
     {
         kkAdminEng.createMailingList(sessionId, search, listOptions);
     }
}
