package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - CreateCatalogPricesFromRules - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class CreateCatalogPricesFromRules
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public CreateCatalogPricesFromRules(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCreateCatalogPricesResult createCatalogPricesFromRules(String sessionId, String catalogId, AdminCreateCatalogPriceOptions options) throws KKAdminException
     {
         return kkAdminEng.createCatalogPricesFromRules(sessionId, catalogId, options);
     }
}
