package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteVendorReview - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteVendorReview
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteVendorReview(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteVendorReview(String sessionId, int reviewId) throws KKAdminException
     {
         kkAdminEng.deleteVendorReview(sessionId, reviewId);
     }
}
