package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteFiltersForCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteFiltersForCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteFiltersForCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteFiltersForCustomer(String sessionId, int userId) throws KKAdminException
     {
         kkAdminEng.deleteFiltersForCustomer(sessionId, userId);
     }
}
