package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteVendor - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteVendor
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteVendor(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteVendor(String sessionId, int vendorId) throws KKAdminException
     {
         kkAdminEng.deleteVendor(sessionId, vendorId);
     }
}
