package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteCustomerMultiStore - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteCustomerMultiStore
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteCustomerMultiStore(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminDeleteCustomerResult deleteCustomerMultiStore(String sessionId, int customerId, String[] stores) throws KKAdminException
     {
         return kkAdminEng.deleteCustomerMultiStore(sessionId, customerId, stores);
     }
}
