package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteProdAttrDescWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteProdAttrDescWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteProdAttrDescWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteProdAttrDescWithOptions(String sessionId, int id, AdminProdAttrDescOptions options) throws KKAdminException
     {
         return kkAdminEng.deleteProdAttrDescWithOptions(sessionId, id, options);
     }
}
