package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteProducts - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteProducts
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteProducts(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteProducts(String sessionId, AdminCommonOptions options) throws KKAdminException
     {
         kkAdminEng.deleteProducts(sessionId, options);
     }
}
