package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeletePromotionWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeletePromotionWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeletePromotionWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deletePromotionWithOptions(String sessionId, int promotionId, AdminDeletePromotionOptions options) throws KKAdminException
     {
         kkAdminEng.deletePromotionWithOptions(sessionId, promotionId, options);
     }
}
