package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteContent - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteContent
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteContent(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteContent(String sessionId, int contentId) throws KKAdminException
     {
         kkAdminEng.deleteContent(sessionId, contentId);
     }
}
