package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomerForIdWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerForIdWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomerForIdWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomer getCustomerForIdWithOptions(String sessionId, int customerId, AdminGetCustomerOptions options) throws KKAdminException
     {
         return kkAdminEng.getCustomerForIdWithOptions(sessionId, customerId, options);
     }
}
