package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetContents - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetContents
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetContents(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminContentSearchResult getContents(String sessionId, AdminContentSearch search, AdminDataDescriptor dataDesc) throws KKAdminException
     {
         return kkAdminEng.getContents(sessionId, search, dataDesc);
     }
}
