package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomerForEmailWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerForEmailWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomerForEmailWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomer getCustomerForEmailWithOptions(String sessionId, String emailAddress, AdminGetCustomerOptions options) throws KKAdminException
     {
         return kkAdminEng.getCustomerForEmailWithOptions(sessionId, emailAddress, options);
     }
}
