package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetContentType - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetContentType
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetContentType(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminContentType getContentType(String sessionId, int contentTypeId) throws KKAdminException
     {
         return kkAdminEng.getContentType(sessionId, contentTypeId);
     }
}
