package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCatalogRules - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCatalogRules
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCatalogRules(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCatalogRule[] getCatalogRules(String sessionId, String catalogId) throws KKAdminException
     {
         return kkAdminEng.getCatalogRules(sessionId, catalogId);
     }
}
