package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetContentTypes - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetContentTypes
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetContentTypes(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminContentTypeSearchResult getContentTypes(String sessionId, AdminContentTypeSearch search, AdminDataDescriptor dataDesc) throws KKAdminException
     {
         return kkAdminEng.getContentTypes(sessionId, search, dataDesc);
     }
}
