package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetFilter - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetFilter
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetFilter(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminFilter getFilter(String sessionId, int Id) throws KKAdminException
     {
         return kkAdminEng.getFilter(sessionId, Id);
     }
}
