package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetFilters - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetFilters
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetFilters(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminFilterSearchResult getFilters(String sessionId, AdminFilterSearch search, AdminDataDescriptor dataDesc) throws KKAdminException
     {
         return kkAdminEng.getFilters(sessionId, search, dataDesc);
     }
}
