package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetReviewsPerVendor - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetReviewsPerVendor
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetReviewsPerVendor(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminReviews getReviewsPerVendor(String sessionId, AdminDataDescriptor dataDesc, int vendorId) throws KKAdminException
     {
         return kkAdminEng.getReviewsPerVendor(sessionId, dataDesc, vendorId);
     }
}
