package com.konakartadmin.app;

import java.util.Calendar;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetStoreTime - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetStoreTime
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetStoreTime(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public Calendar getStoreTime() throws KKAdminException
     {
         return kkAdminEng.getStoreTime();
     }
}
