package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetStoresForCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetStoresForCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetStoresForCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminStore[] getStoresForCustomer(String sessionId, String emailAddress) throws KKAdminException
     {
         return kkAdminEng.getStoresForCustomer(sessionId, emailAddress);
     }
}
