package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetVendorReviews - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetVendorReviews
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetVendorReviews(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminReviews getVendorReviews(String sessionId, AdminDataDescriptor dataDesc, AdminReviewSearch revSearch) throws KKAdminException
     {
         return kkAdminEng.getVendorReviews(sessionId, dataDesc, revSearch);
     }
}
