package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetVendorForId - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetVendorForId
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetVendorForId(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminVendor getVendorForId(String sessionId, int vendorId) throws KKAdminException
     {
         return kkAdminEng.getVendorForId(sessionId, vendorId);
     }
}
