package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetVendors - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetVendors
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetVendors(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminVendorSearchResult getVendors(String sessionId, AdminVendorSearch vendorSearch, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getVendors(sessionId, vendorSearch, offset, size);
     }
}
