package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertFilter - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertFilter
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertFilter(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertFilter(String sessionId, AdminFilter filter) throws KKAdminException
     {
         return kkAdminEng.insertFilter(sessionId, filter);
     }
}
