package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertContent - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertContent
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertContent(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertContent(String sessionId, AdminContent content) throws KKAdminException
     {
         return kkAdminEng.insertContent(sessionId, content);
     }
}
