package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RenameFiles - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RenameFiles
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RenameFiles(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public boolean renameFiles(String sessionId, String[] srcFileNames, String[] dstFileNames) throws KKAdminException
     {
         return kkAdminEng.renameFiles(sessionId, srcFileNames, dstFileNames);
     }
}
