package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateVendor - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateVendor
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateVendor(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateVendor(String sessionId, AdminVendor vendor) throws KKAdminException
     {
         kkAdminEng.updateVendor(sessionId, vendor);
     }
}
