package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateCustomerWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateCustomerWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateCustomerWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateCustomerWithOptions(String sessionId, AdminCustomer customer, AdminUpdateCustomerOptions options) throws KKAdminException
     {
         kkAdminEng.updateCustomerWithOptions(sessionId, customer, options);
     }
}
