package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateContentType - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateContentType
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateContentType(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateContentType(String sessionId, AdminContentType content) throws KKAdminException
     {
         kkAdminEng.updateContentType(sessionId, content);
     }
}
