package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateContent - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateContent
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateContent(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateContent(String sessionId, AdminContent content) throws KKAdminException
     {
         kkAdminEng.updateContent(sessionId, content);
     }
}
