package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateFilter - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateFilter
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateFilter(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateFilter(String sessionId, AdminFilter filter) throws KKAdminException
     {
         kkAdminEng.updateFilter(sessionId, filter);
     }
}
